### Ingest Stock Data (CSV Upload)
# Make sure sample.csv exists in the specified path or project root
POST http://localhost:8081/api/stocks/upload
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="file"; filename="sample.csv"
Content-Type: text/csv

< ./sample.csv
--boundary--

### Get Stock Prices (AAPL)
GET http://localhost:8081/api/stocks/ARKK
Accept: application/json

### Get Stock Prices with Date Range
GET http://localhost:8081/api/stocks/ARKK?startDate=2020-01-01&endDate=2023-12-31
Accept: application/json

### Run Backtest (RSI Strategy)
POST http://localhost:8082/api/analysis/backtest?symbol=ARKK&strategy=Swing Trading Strategy (7-20 Days)
Accept: application/json

### Run Buld upload of Stock Data from Directory
POST http://localhost:8081/api/stocks/bulk-upload?rootPath=C:\Users\pemba\git\stock-data
Accept: application/json

### Delete Stock Data
DELETE http://localhost:8081/api/stocks/ARKK
Accept: application/json

### Run Pro Backtest (v2)
POST http://localhost:8082/api/v2/analysis/backtest?symbol=AAPL&strategyName=MacdTrendPro&capital=10000&from=2014-01-01&to=2024-12-31
Accept: application/json

### Run Pro Backtest CSV Download
GET http://localhost:8082/api/v2/analysis/backtest/csv?symbol=AAPL&strategyName=MacdTrendPro&capital=10000
Accept: text/csv

### Run Backtest with DSL
POST http://localhost:8082/api/v2/dsl/backtest?symbol=APPL
Content-Type: text/plain

strategy "RSI" {
    indicator "rsi" as r1 { period = 14 }
    buy when { r1 < 20 }
    sell when { r1 > 80 }
}

### Start Live Trading
POST http://localhost:8082/api/v2/live/start?symbol=ARKK&strategyName=RSI
Accept: application/json

### Stop Live Trading
POST http://localhost:8082/api/v2/live/stop?symbol=ARKK
Accept: application/json

### Start Paper Trading
POST http://localhost:8082/api/v2/paper/start?symbol=ARKK&strategyName=CandlestickPro&initialCapital=100000
Accept: application/json

### Stop Paper Trading
POST http://localhost:8082/api/v2/paper/stop?sessionId=791a414f-f716-4b3e-a1f9-f1a7f2a11537
Accept: application/json

### Get Paper Trading Status
GET http://localhost:8082/api/v2/paper/status?sessionId=SESSION_ID_HERE
Accept: application/json