### Ingest Stock Data (CSV Upload)
# Make sure sample.csv exists in the specified path or project root
POST http://localhost:8081/api/stocks/upload
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="file"; filename="sample.csv"
Content-Type: text/csv

< ./sample.csv
--boundary--

### Get Stock Prices (AAPL)
GET http://localhost:8081/api/stocks/ARKK
Accept: application/json

### Get Stock Prices with Date Range
GET http://localhost:8081/api/stocks/ARKK?startDate=2020-01-01&endDate=2023-12-31
Accept: application/json

### Run Backtest (RSI Strategy)
POST http://localhost:8082/api/analysis/backtest?symbol=ARKK&strategy=RSI Strategy
Accept: application/json

### Run Buld upload of Stock Data from Directory
POST http://localhost:8081/api/stocks/bulk-upload?rootPath=C:\Users\pemba\git\stock-data
Accept: application/json